//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VapeForLife.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class base_languages_relation
    {
        public int idbase_languages_relation { get; set; }
        public int idfBase { get; set; }
        public int idfLanguages { get; set; }
        public string CaptionTranslation { get; set; }
        public string DescriptionTranslation { get; set; }
    }
}
