//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VapeForLife.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class @base
    {
        public int IdBase { get; set; }
        public string Caption { get; set; }
        public string Description { get; set; }
        public int PG { get; set; }
        public int VG { get; set; }
        public int Water { get; set; }
        public int Nicotin { get; set; }
    }
}
