//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VapeForLife.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class languages
    {
        public int IdLanguages { get; set; }
        public string Caption { get; set; }
        public string CountryCode { get; set; }
    }
}
